# Data Preprocessing

+ Data Augmentation
    + Resize the images to the same size.
+ Split dataset for train and test

## Import Library

In [120]:
import os
import numpy as np
import pandas as pd

import cv2 as cv

In [121]:
path  = './dataset'
files = os.listdir(path)

# Rename folder of each class 
folder_name =[]
for i in files:
    folder_name.append(i.replace('_',' ').replace('-',' '))

labels = dict()
for j in range(len(files)):
    labels[folder_name[j]] = os.listdir(path+'/'+files[j])

data = []
for i in range(len(files)):
    for j in range(len(labels[folder_name[i]])):
        data.append([path+'/'+files[i]+'/'+labels[folder_name[i]][j],folder_name[i]])

# to convert the list into dataframe
df = pd.DataFrame(data,columns=['image','label'])

In [122]:
# read the images and convert them into array and fit it model
X = df['image']
y = df['label']
df1 = []

# Image transformation
for i in range(len(X)):
    img = cv.imread(X[i])

    # Resize the image to 255
    img = cv.resize(img,(255,1))
    # Flatten the image
    img = img.flatten()

    # Convert the image into array
    img = np.ravel(img)
    
    df1.append(img)
    X[i]=pd.DataFrame([df1[i]])

X = pd.DataFrame(df1)

In [123]:
X

,0,1,2,3,4,5,6,7,8,9,...,755,756,757,758,759,760,761,762,763,764
0,54,57,62,42,46,51,32,36,41,31,...,101,98,119,116,57,80,76,90,112,110
1,250,198,177,248,199,176,245,198,176,240,...,56,16,67,54,20,81,68,34,105,98
2,107,113,112,100,106,105,101,107,106,97,...,63,51,57,56,43,49,48,37,42,43
3,15,22,28,3,4,11,8,7,13,33,...,131,36,54,67,79,96,108,48,66,76
4,135,101,51,134,97,37,144,108,48,184,...,166,194,193,174,209,188,190,206,193,186
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
824,82,158,224,87,163,229,80,156,222,81,...,229,80,124,171,60,94,140,65,99,145
825,9,84,68,38,117,100,52,136,118,38,...,194,164,184,198,169,188,203,137,157,174
826,97,176,252,87,164,241,81,156,233,80,...,212,81,154,220,88,161,229,90,164,232
827,55,218,229,33,210,220,13,209,215,3,...,177,1,179,181,0,182,184,0,188,189
828,101,184,218,111,184,215,120,184,212,118,...,181,79,193,233,98,206,242,82,185,218

In [124]:
y

0      almond
1      almond
2      almond
3      almond
4      almond
        ...
824     wheat
825     wheat
826     wheat
827     wheat
828     wheat
Name: label, Length: 829, dtype: object